"""initial migration

Revision ID: ca0a0303a18c
Revises: 
Create Date: 2025-03-02 19:15:24.393818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0a0303a18c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('homepage', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('cookie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('cookie_value', sa.Text(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('total_used', sa.Integer(), nullable=True),
    sa.Column('daily_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cookie')
    op.drop_table('website')
    # ### end Alembic commands ###
